from .admin import AdminViewSet
from .parent import ParentViewSet
from .student import StudentViewSet
from .teacher import TeacherViewSet
from .user import UserViewSet
from .user import UserCreate
from .stage import StageViewSet
from .category import CategoryViewSet
from .subject import SubjectViewSet
from .questionnair import QuestionnairViewSet
from .qanswer import QanswerViewSet