# Generated by Django 3.0.3 on 2020-04-29 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 29), null=True, verbose_name='Birth date'),
        ),
    ]
