# Generated by Django 3.0.3 on 2020-04-30 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200429_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Hire date'),
        ),
    ]
