# Generated by Django 3.0.3 on 2020-05-02 15:33

import api.models.material
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200502_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.CharField(choices=[('AUD', 'Audio'), ('TXT', 'TEXT/PDF'), ('VID', 'Video')], max_length=3)),
                ('path', models.FileField(upload_to=api.models.material.subject_directory_path)),
                ('title', models.CharField(max_length=30)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subject')),
            ],
        ),
    ]
