# Generated by Django 3.0.3 on 2020-05-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200501_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
