# Generated by Django 3.0.3 on 2020-05-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200502_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='path',
            field=models.FileField(upload_to='material'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_image'),
        ),
    ]
