# Generated by Django 3.0.3 on 2020-07-10 22:13

import api.models.material
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exam_examquestion_material_questionanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnswer',
            new_name='ExamQuestionAnswer',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ManyToManyField(null=True, to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='path',
            field=models.FileField(max_length=500, upload_to=api.models.material.user_directory_path),
        ),
    ]
