# Generated by Django 3.0.8 on 2020-07-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200711_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='correct',
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.FloatField(),
        ),
    ]
