# Generated by Django 3.0.8 on 2020-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200718_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
